Traceback (most recent call last):
  File "/usr/local/bin/nosetests", line 11, in <module>
    sys.exit(run_exit())
  File "/usr/local/lib/python2.7/dist-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/local/lib/python2.7/dist-packages/nose/core.py", line 145, in parseArgs
    self.config.configure(argv, doc=self.usage())
  File "/usr/local/lib/python2.7/dist-packages/nose/config.py", line 325, in configure
    self.configureWhere(options.where)
  File "/usr/local/lib/python2.7/dist-packages/nose/config.py", line 420, in configureWhere
    "not a directory" % path)
ValueError: Working directory 'tests' not found, or not a directory
